// src/format/cursor-rule.ts
// `setup cursor` 写的规则文件（D038）。Cursor 没有能在压缩后注入的钩子：preCompact 只能观察，beforeSubmitPrompt
// 不能注入（官方文档）。`alwaysApply: true` 的规则始终在上下文里——指针与「察觉到被压缩就跑 todopi prime」因此活过
// 压缩。它也是 FR-A2b 要的回退：CLI 的钩子支持一直在变，规则文件不依赖钩子。内容是静态的指针，不是 prime 的输出。
//
// 标记在第二行（第一行必须是 frontmatter 的 `---`）：description 字段本身就是标记。

import { ensureGeneratedFile, type GeneratedFileResult } from "./generated-file.ts";

export const CURSOR_RULE_MARKER = "description: todopi task ledger pointer (generated by `todopi setup cursor`; re-running setup replaces this file)";

export const CURSOR_RULE = `---
${CURSOR_RULE_MARKER}
alwaysApply: true
---
This repository tracks work in a todopi ledger (\`.todopi/\`); the protocol is in AGENTS.md.

- To see what you are working on, run \`todopi prime\` (the full picture: \`todopi prime --full\`).
- When you notice your context was summarized or compacted, run \`todopi prime\` before continuing — no hook will do it for you.
`;

export function ensureCursorRule(path: string): GeneratedFileResult {
  return ensureGeneratedFile(path, CURSOR_RULE, CURSOR_RULE_MARKER, 1);
}
