// src/format/opencode-plugin.ts
// `setup opencode` 写的插件（PRD FR-A2；2026-09-26 在 OpenCode 1.18.15 上实测会话开始注入，见 PRD §17）。
//
// OpenCode 没有「钩子的 stdout 进上下文」这回事：`event` 钩子只能观察。所以插件在 `session.created` 与
// `session.compacted` 时跑 `todopi prime --hook`（会话 id 作为 `{"sessionID": …}` 喂进 stdin），把输出按会话缓存，
// 再经 `experimental.chat.system.transform` 追加进系统提示——系统提示天然活过压缩；也不会每一轮都跑 prime
// （每跑一次都会刷新 handoff 的会话基准）。本进程里没见过 created 的会话（续接的旧会话）第一次用到时补跑一次。
//
// 这个文件是我们生成的，带标记头：已有且带标记就**整份替换**；已有却没有标记，那是用户自己的文件，拒绝。标记只是
// 约定，不是证明——用户若在带标记的文件里改动或照抄这个开头，重跑 setup 会覆盖它；标记那一行写明了这一点。
// 符号链接（含悬空的）一律拒绝。

import { lstatSync, mkdirSync, readFileSync } from "node:fs";
import { lstatOrNull } from "./claude-settings.ts";
import { dirname } from "node:path";
import { writeFileAtomic } from "../fs/atomic.ts";
import { EXIT, CliError } from "../exit.ts";

export const PLUGIN_MARKER = "// Generated by `todopi setup opencode`.";

export const OPENCODE_PLUGIN = `${PLUGIN_MARKER} Re-running setup replaces any file starting with this line; edits are lost.
// Injects \`todopi prime\` output into the system prompt: refreshed when a session is created and after it is
// compacted, cached per session in between.
export const TodopiPlugin = async ({ $, directory }) => {
  const primed = new Map();
  const prime = async (sessionID) => {
    const payload = Buffer.from(JSON.stringify({ sessionID }));
    const r = await $\`todopi prime --hook < \${payload}\`.cwd(directory).quiet().nothrow();
    // Failed (e.g. todopi not on PATH yet): don't cache, so the next model call retries.
    if (r.exitCode === 0) primed.set(sessionID, r.stdout.toString().trim());
    else primed.delete(sessionID);
  };
  return {
    event: async ({ event }) => {
      if (event.type === "session.created") await prime(event.properties.info.id);
      else if (event.type === "session.compacted") await prime(event.properties.sessionID);
    },
    "experimental.chat.system.transform": async (input, output) => {
      if (!input.sessionID) return;
      if (!primed.has(input.sessionID)) await prime(input.sessionID);
      const text = primed.get(input.sessionID);
      if (text) output.system.push(text);
    },
  };
};
`;

export type PluginResult = "created" | "updated" | "unchanged";

export function ensureOpencodePlugin(path: string): PluginResult {
  // lstat 判断存在：悬空符号链接也是「有东西」，不能当空位（F15 评审）。
  const link = lstatOrNull(path);
  if (link?.isSymbolicLink() === true) throw new CliError(EXIT.usage, `${path} is a symbolic link; left untouched.`);
  if (link === null) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileAtomic(path, OPENCODE_PLUGIN);
    return "created";
  }
  const current = readFileSync(path, "utf8");
  if (current === OPENCODE_PLUGIN) return "unchanged";
  if (!current.startsWith(PLUGIN_MARKER)) {
    throw new CliError(EXIT.usage, `${path} exists and was not written by todopi; left untouched. Move it aside, then run setup again.`);
  }
  writeFileAtomic(path, OPENCODE_PLUGIN, lstatSync(path).mode);
  return "updated";
}
