// src/format/opencode-plugin.ts
// `setup opencode` 写的插件（PRD FR-A2；2026-09-26 在 OpenCode 1.18.15 上实测会话开始注入，见 PRD §17）。
//
// OpenCode 没有「钩子的 stdout 进上下文」这回事：`event` 钩子只能观察。所以插件在 `session.created` 与
// `session.compacted` 时跑 `todopi prime --hook`（会话 id 作为 `{"sessionID": …}` 喂进 stdin），把输出按会话缓存，
// 再经 `experimental.chat.system.transform` 追加进系统提示——系统提示天然活过压缩；也不会每一轮都跑 prime
// （每跑一次都会刷新 handoff 的会话基准）。本进程里没见过 created 的会话（续接的旧会话）第一次用到时补跑一次。
//
// 这个文件是我们生成的，带标记头：已有且带标记就**整份替换**；已有却没有标记，那是用户自己的文件，拒绝。标记只是
// 约定，不是证明——用户若在带标记的文件里改动或照抄这个开头，重跑 setup 会覆盖它；标记那一行写明了这一点。
// 符号链接（含悬空的）一律拒绝。

import { ensureGeneratedFile, type GeneratedFileResult } from "./generated-file.ts";

/**
 * 标记是**整个第一行**。判据是「第一行与它逐字相同」——代码认的与提示写的是同一段文字（F15 评审二轮：曾只比前缀，
 * 一个开头相同、其余是用户自己写的首行也会被当成我们的文件覆盖）。
 */
export const PLUGIN_MARKER = "// Generated by `todopi setup opencode`. Re-running setup replaces any file whose first line is exactly this line; edits are lost.";

export const OPENCODE_PLUGIN = `${PLUGIN_MARKER}
// Injects \`todopi prime\` output into the system prompt: refreshed when a session is created and after it is
// compacted, cached per session in between.
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";

// Is there a .todopi/ at or above dir? Cheap check, so an empty result (no ledger yet) is retried only once one appears.
const hasLedger = (dir) => {
  for (let d = dir; ; d = dirname(d)) {
    if (existsSync(join(d, ".todopi"))) return true;
    if (dirname(d) === d) return false;
  }
};

export const TodopiPlugin = async ({ $, directory }) => {
  const primed = new Map();
  const prime = async (sessionID) => {
    const payload = Buffer.from(JSON.stringify({ sessionID }));
    const r = await $\`todopi --agent opencode prime --hook < \${payload}\`.cwd(directory).quiet().nothrow();
    // Failed (e.g. todopi not on PATH yet): don't cache, so the next model call retries.
    if (r.exitCode === 0) primed.set(sessionID, r.stdout.toString().trim());
    else primed.delete(sessionID);
  };
  return {
    event: async ({ event }) => {
      if (event.type === "session.created") await prime(event.properties.info.id);
      else if (event.type === "session.compacted") await prime(event.properties.sessionID);
    },
    "experimental.chat.system.transform": async (input, output) => {
      if (!input.sessionID) return;
      // Not primed yet, or primed empty (no ledger then) and a ledger has appeared since: prime now.
      if (!primed.has(input.sessionID) || (primed.get(input.sessionID) === "" && hasLedger(directory))) await prime(input.sessionID);
      const text = primed.get(input.sessionID);
      if (text) output.system.push(text);
    },
  };
};
`;

export type PluginResult = GeneratedFileResult;

export function ensureOpencodePlugin(path: string): PluginResult {
  return ensureGeneratedFile(path, OPENCODE_PLUGIN, PLUGIN_MARKER);
}
