// src/format/pi-extension.ts
// `setup pi` 写的扩展（PRD FR-A2；2026-09-26 在 pi 0.84.0 上实测，见 PRD §17）。
//
// 与 OpenCode 插件同构：`session_start` 时跑 `todopi prime`、按会话缓存，`session_compact`（压缩**之后**；
// `session_before_compact` 是之前）刷新，`before_agent_start` 把缓存追加进本轮的系统提示——pi 文档写明它能改
// 系统提示，本轮有效、不写进会话。会话 id 由 `ctx.sessionManager.getSessionId()` 自取（不在事件参数里），
// 经 `--session` 传给 prime：`pi.exec` 没有 stdin 选项（子进程 stdin 是 ignore，`--hook` 读 stdin 立刻结束，
// 不会卡住）。`--hook` 仍然要：没有账本的项目里静默退出 0（用户级扩展在每个项目里都会加载）。那时缓存的是空结果：
// 之后每一轮只做一次便宜的文件系统检查，出现了 `.todopi/`（同一会话里 init 了）才重跑——不每轮都起 node 进程
// （F16 评审：空结果曾被永久缓存）。

import { ensureGeneratedFile, type GeneratedFileResult } from "./generated-file.ts";

export const PI_MARKER = "// Generated by `todopi setup pi`. Re-running setup replaces any file whose first line is exactly this line; edits are lost.";

export const PI_EXTENSION = `${PI_MARKER}
// Injects \`todopi prime\` output into the system prompt: refreshed on session start and after compaction,
// cached per session in between.
import { existsSync } from "node:fs";
import { dirname, join } from "node:path";

// Is there a .todopi/ at or above dir? Cheap check, so an empty result (no ledger yet) is retried only once one appears.
const hasLedger = (dir) => {
  for (let d = dir; ; d = dirname(d)) {
    if (existsSync(join(d, ".todopi"))) return true;
    if (dirname(d) === d) return false;
  }
};

export default function (pi) {
  const primed = new Map();
  const prime = async (ctx) => {
    const id = ctx.sessionManager.getSessionId();
    const r = await pi.exec("todopi", ["prime", "--hook", "--session", id], { cwd: ctx.cwd, timeout: 30000 });
    // Failed (e.g. todopi not on PATH yet): don't cache, so the next turn retries.
    if (r.code === 0) primed.set(id, r.stdout.trim());
    else primed.delete(id);
  };
  pi.on("session_start", async (_event, ctx) => { await prime(ctx); });
  pi.on("session_compact", async (_event, ctx) => { await prime(ctx); });
  pi.on("before_agent_start", async (event, ctx) => {
    const id = ctx.sessionManager.getSessionId();
    // Not primed yet, or primed empty (no ledger then) and a ledger has appeared since: prime now.
    if (!primed.has(id) || (primed.get(id) === "" && hasLedger(ctx.cwd))) await prime(ctx);
    const text = primed.get(id);
    if (!text) return;
    return { systemPrompt: \`\${event.systemPrompt}\\n\\n\${text}\` };
  });
}
`;

export function ensurePiExtension(path: string): GeneratedFileResult {
  return ensureGeneratedFile(path, PI_EXTENSION, PI_MARKER);
}
