#!/usr/bin/env node
// tools/brew/formula.mjs —— 按一次发布的 SHA256SUMS 生成 Homebrew formula（首发清单 §13：brew tap；F34）。
//
// 用法：node tools/brew/formula.mjs <version> <SHA256SUMS 文件> [下载地址的前缀]
//   前缀默认 https://github.com/seandong/todopi/releases/download/v<version>；测试与本地实测用 file:// 前缀。
// 输出到 stdout：Formula/todopi.rb。四个平台（macOS / Linux × arm64 / x64）各取 release 里的单文件二进制，
// 每个都带 sha256——Homebrew 下载后校验，不符就拒绝安装。二进制自带运行时，所以 formula 没有依赖；`tp` 是同一个命令的别名。
//
// 哪个平台的资产缺了、SHA256SUMS 里对不上、版本号不像版本号，都直接失败，不生成一份装不上的 formula。

import { readFileSync } from "node:fs";

const [version, sumsPath, baseArg] = process.argv.slice(2);
const die = (m) => { process.stderr.write(`formula: ${m}\n`); process.exit(1); };
if (!version || !sumsPath) die("usage: node tools/brew/formula.mjs <version> <SHA256SUMS> [base-url]");
if (!/^\d+\.\d+\.\d+(-[0-9A-Za-z.-]+)?$/.test(version)) die(`${JSON.stringify(version)} is not a version number`);
const base = (baseArg ?? `https://github.com/seandong/todopi/releases/download/v${version}`).replace(/\/+$/, "");

// SHA256SUMS：每行 `<64 位十六进制>  <文件名>`（sha256sum 的格式；二进制模式的 `*` 前缀也认）
const sums = new Map();
for (const line of readFileSync(sumsPath, "utf8").split("\n")) {
  const m = /^([0-9a-f]{64}) [ *](\S+)$/.exec(line.trim());
  if (!m) continue;
  // 同一个文件出现两次、校验和却不同：说不清哪个对，不按行序挑一个（F34 评审）；一模一样的重复无害
  if (sums.has(m[2]) && sums.get(m[2]) !== m[1]) die(`${sumsPath} lists ${m[2]} twice with different checksums`);
  sums.set(m[2], m[1]);
}

const PLATFORMS = [
  ["macos", "arm", "darwin-arm64"], ["macos", "intel", "darwin-x64"],
  ["linux", "arm", "linux-arm64"], ["linux", "intel", "linux-x64"],
];
const asset = (p) => `todopi-${version}-${p}.tar.gz`;
for (const [, , p] of PLATFORMS) if (!sums.has(asset(p))) die(`${sumsPath} has no checksum for ${asset(p)}`);

const block = (os) => PLATFORMS.filter(([o]) => o === os).map(([, cpu, p]) => `    on_${cpu} do
      url "${base}/${asset(p)}"
      sha256 "${sums.get(asset(p))}"
    end`).join("\n");

process.stdout.write(`# Generated by tools/brew/formula.mjs for todopi ${version}. Do not edit by hand: the release workflow regenerates it.
class Todopi < Formula
  desc "Durable task ledger for AI coding agents"
  homepage "https://github.com/seandong/todopi"
  version "${version}"
  license "MIT"

  on_macos do
${block("macos")}
  end

  on_linux do
${block("linux")}
  end

  def install
    bin.install "todopi"
    bin.install_symlink "todopi" => "tp"
  end

  test do
    assert_equal "${version}", shell_output("#{bin}/todopi --version").strip
    system bin/"todopi", "init"
    assert_path_exists testpath/".todopi/config.yml"
  end
end
`);
